import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignUp,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <section className=" min-h-screen w-screen flex justify-center  items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignUp/>
            </SignedOut>
            <SignedIn>
                        {children}
            </SignedIn>
          </section>
        </body>
      </html>
    </ClerkProvider>
  )
}